In [1]:
# GOAL: 1. Import dataset 2. Train Classifier 3. Predict Labels 4. Visualize The Tree | Reference: https://www.youtube.com/watch?v=tNa99PG8hR8&list=RDcKxRvEZd3Mw&index=2

In [2]:
# 1. IMPORT DATA

In [3]:
from sklearn.datasets import load_iris


In [4]:
# Load iris dataset (built in scikit) 
iris = load_iris()
# print (iris)

In [5]:
# Render features and target names from iris dataset
print (iris.feature_names)
print (iris.target_names)

# Load the feature per index
print (iris.data[0])

# Load the labels
print (iris.target[0]) # Resut of 0 means it's a sentoza

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


In [6]:
#2 TRAIN CLASSIFIER

In [7]:
import numpy as np

In [8]:
# Create array reference index
test_idx = [0,50,100]

In [9]:
# Training data 
train_target = np.delete (iris.target, test_idx)
train_data = np.delete (iris.data, test_idx, axis=0)

# Testing Data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [10]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print (test_target)

[0 1 2]


In [11]:
print (test_target)
print (clf.predict(test_data))

[0 1 2]
[0 1 2]


In [13]:
# Manipulate & Test
import pandas as pd
iris_pd = pd.DataFrame(iris)

ValueError: arrays must all be same length

In [ ]:
Test